### ISSUE TITLE
Updated stats on dashboard

### ISSUE THREAD

**Issue by orblivion** [lbryio/wallet-sync-server#22]
I added a new counter to Prometheus to track two different errors. They both trigger when a channel related to websockets get overwhelmed. One is for removing users on password change, the other is updating clients when the wallet is updated. But I could add any arbitrarily of course.

I also split "method" in the request counter into "method" and "endpoint".

# Counters

## Request Count
* Name: `wallet_sync_requests_count`
* Fields: `method`, `endpoint`

## Error Count
* Name: `wallet_sync_error_count`
* Fields: `error_type`

# TODO

- [x] Better tags
- [x] Put on dashboard.
- [x] Do we need to explicitly add new `details` values to the dashboard as I add them to the server?

# Reference:
* [Definitions](https://github.com/lbryio/wallet-sync-server/blob/master/metrics/metrics.go)
* [Error 1](https://github.com/lbryio/wallet-sync-server/commit/4f074b181c1b53e9155565b1863bf8f1ab955810#diff-c41ac3e70d598112211df833e1c45f74c34bf9c393970e7dc636fde5853271e4R147)
* [Error 2](https://github.com/lbryio/wallet-sync-server/commit/4f074b181c1b53e9155565b1863bf8f1ab955810#diff-5aa7ea07bc25f6d35f59b1d627dcee9d42d4136fdb8ce5053471e8c76a7d0187R158)

**Comment by orblivion** [comment]
This code isn't live yet fyi.

**Comment by orblivion** [comment]
https://github.com/lbryio/wallet-sync-server/commit/afc43a00680ddeb0d68326eed4a2cde2aed596f8

**Comment by orblivion** [comment]
@lyoshenka Updated with the latest.

**Comment by lyoshenka** [comment]
its on the dash
